apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerbuilder-config
  labels:
    heritage: drycc
data:
  images.json: |
    [
        {
            "name": "container",
            "image": "{{.Values.docker_registry}}{{.Values.org}}/dockerbuilder:{{.Values.docker_tag}}"
        }
    ]
  pull_policy: {{ .Values.pull_policy }}
