name: imagebuilder
home: https://github.com/drycc/imagebuilder
version: v1.0.0
description: Drycc imagebuilder builds your app from a Dockerfile inside a Kubernetes pod, used by Drycc Workflow.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
