apiVersion: v1
kind: ConfigMap
metadata:
  name: imagebuilder-config
  labels:
    heritage: drycc
data:
  images.json: |
    [
        {
            "name": "container",
            "image": "{{.Values.image_registry}}{{.Values.org}}/imagebuilder:{{.Values.image_tag}}"
        }
    ]
  image_pull_policy: {{ .Values.image_pull_policy }}
