name: dockerbuilder
home: https://github.com/dryccthree/dockerbuilder
version: <Will be populated by the ci before publishing the chart>
description: Drycc dockerbuilder builds your app from a Dockerfile inside a Kubernetes pod, used by Drycc Workflow.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
